name: 'pull request'

on:
  push:
    branches:
      - feature/netlify

jobs:
  deploy:
    name: 'Deploy to Netlify'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          build_command: ''